# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import networkx as nx
from sklearn.preprocessing import MinMaxScaler
from networkx.algorithms.community import greedy_modularity_communities

st.set_page_config(layout="wide")

st.title("🌐 Global Cyber Conflict Intelligence Dashboard")

# -----------------------------
# Load Data
# -----------------------------
@st.cache_data
def load_data():
    df = pd.read_excel("Cyber_Incidents_Dyadic.xlsx")
    df["start_date"] = pd.to_datetime(df["start_date"], errors="coerce")
    df["year"] = df["start_date"].dt.year
    return df

df = load_data()

# -----------------------------
# Sidebar Filters
# -----------------------------
st.sidebar.header("Filters")

years = sorted(df["year"].dropna().unique())
selected_year = st.sidebar.selectbox("Select Year (or All)", ["All"] + list(years))

if selected_year != "All":
    df = df[df["year"] == selected_year]

# =============================
# 🌍 WORLD MAP SECTION
# =============================
st.header("🌍 Global Cyber Activity Map")

initiator_counts = (
    df.groupby("initiator_country")["incident_id"]
    .count()
    .reset_index()
)

initiator_counts.columns = ["country", "attack_count"]
initiator_counts["log_attack"] = np.log1p(initiator_counts["attack_count"])

fig_map = px.choropleth(
    initiator_counts,
    locations="country",
    locationmode="country names",
    color="log_attack",
    color_continuous_scale="Reds",
    title="Cyber Attacks Initiated (Log Scaled)"
)

st.plotly_chart(fig_map, use_container_width=True)

# =============================
# 📈 INTENSITY TREND
# =============================
st.header("📈 Cyber Intensity Trend")

intensity_trend = (
    df.groupby("year")["weighted_intensity"]
    .mean()
    .reset_index()
)

fig_trend = px.line(
    intensity_trend,
    x="year",
    y="weighted_intensity",
    markers=True,
    title="Average Weighted Intensity Over Time"
)

st.plotly_chart(fig_trend, use_container_width=True)

# =============================
# 🧠 BLOC ANALYSIS
# =============================
st.header("🧠 Bloc-Based Attack Specialization")

edges = (
    df.groupby(["initiator_country", "receiver_country"])
    .size()
    .reset_index(name="weight")
)

G = nx.from_pandas_edgelist(
    edges,
    source="initiator_country",
    target="receiver_country",
    edge_attr="weight",
    create_using=nx.DiGraph()
)

G_undirected = G.to_undirected()
communities = list(greedy_modularity_communities(G_undirected))

bloc_map = {}
for i, comm in enumerate(communities):
    for country in comm:
        bloc_map[country] = f"Bloc {i+1}"

df["bloc"] = df["initiator_country"].map(bloc_map)

attack_cols = [
    "Data theft",
    "Data theft & Doxing",
    "Disruption",
    "Hijacking with Misuse",
    "Hijacking without Misuse",
    "Ransomware"
]

bloc_attack = (
    df.groupby("bloc")[attack_cols]
    .mean()
    .reset_index()
)

bloc_melt = bloc_attack.melt(
    id_vars="bloc",
    var_name="Attack Type",
    value_name="Specialization Rate"
)

fig_bloc = px.density_heatmap(
    bloc_melt,
    x="Attack Type",
    y="bloc",
    z="Specialization Rate",
    color_continuous_scale="Viridis",
)

st.plotly_chart(fig_bloc, use_container_width=True)

# =============================
# ⚔ STATE VS NON-STATE
# =============================
st.header("⚔ State vs Non-State Dominance")

category_analysis = (
    df.groupby("initiator_category")
    .agg({
        "incident_id": "count",
        "weighted_intensity": "mean",
        "economic_impact_value": "sum"
    })
    .reset_index()
)

category_analysis.columns = [
    "Category",
    "Total Incidents",
    "Avg Intensity",
    "Economic Damage"
]

col1, col2 = st.columns(2)

with col1:
    fig_pie = px.pie(
        category_analysis,
        names="Category",
        values="Total Incidents",
        title="Incident Share"
    )
    st.plotly_chart(fig_pie, use_container_width=True)

with col2:
    fig_bar = px.bar(
        category_analysis,
        x="Category",
        y="Avg Intensity",
        title="Average Intensity"
    )
    st.plotly_chart(fig_bar, use_container_width=True)

# =============================
# 🕸 NETWORK GRAPH
# =============================
st.header("🕸 Cyber Power Network")

degree = nx.degree_centrality(G)
betweenness = nx.betweenness_centrality(G, weight="weight")

centrality_df = pd.DataFrame({
    "country": list(G.nodes()),
    "degree": [degree[n] for n in G.nodes()],
    "betweenness": [betweenness[n] for n in G.nodes()]
})

activity = (
    df["initiator_country"].value_counts() +
    df["receiver_country"].value_counts()
).fillna(0)

centrality_df["activity"] = centrality_df["country"].map(activity)

scaler = MinMaxScaler((10, 40))
centrality_df["size"] = scaler.fit_transform(
    centrality_df[["activity"]]
)

pos = nx.spring_layout(G, seed=42)

edge_x = []
edge_y = []

for edge in G.edges():
    x0, y0 = pos[edge[0]]
    x1, y1 = pos[edge[1]]
    edge_x += [x0, x1, None]
    edge_y += [y0, y1, None]

edge_trace = go.Scatter(
    x=edge_x,
    y=edge_y,
    mode="lines",
    line=dict(width=0.5, color="#888"),
    hoverinfo="none"
)

node_x = []
node_y = []
node_size = []
node_text = []

for node in G.nodes():
    x, y = pos[node]
    node_x.append(x)
    node_y.append(y)

    row = centrality_df[centrality_df["country"] == node].iloc[0]
    node_size.append(row["size"])

    node_text.append(
        f"{node}<br>"
        f"Degree: {row['degree']:.3f}<br>"
        f"Betweenness: {row['betweenness']:.3f}"
    )

node_trace = go.Scatter(
    x=node_x,
    y=node_y,
    mode="markers",
    hoverinfo="text",
    text=node_text,
    marker=dict(
        size=node_size,
        color=node_size,
        colorscale="Reds",
        showscale=False
    )
)

fig_network = go.Figure(data=[edge_trace, node_trace])
st.plotly_chart(fig_network, use_container_width=True)